### ISSUE TITLE
401 unauthorised issue

### ISSUE THREAD

**Issue by creativetechnologist** [slate-studio/activeadmin-settings#16]
Hi,

I'm getting the following error when updating a setting ...

Started PUT "/admin/settings/32" for 127.0.0.1 at 2013-07-17 08:31:55 +0100
Processing by ActiveadminSettings::SettingsController#update as */*
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"DXK9R5Pb2uwvlPT+xTk3WytF15w6yLvpF6TSqDtZRFg=", "setting"=>{"string"=>"33333"}, "id"=>"32"}
Completed 401 Unauthorized in 61ms

I'm using the following gem versions ...

  * activeadmin (0.5.1)
  * activeadmin-settings (0.4.4)

I'm not sure if this is related to the issue but I recently changed the model that activeadmin uses for login/authentication.

Any help most appreciated as this gem is now being used in a production environment.

**Comment by caifara** [comment]
I'm going to make a pull-request for this, but for now:

When I changed the authentication settings of ActiveAdmin I bumped into this issue. I let refinery handle the logic, so in ActiveAdmin I use: 

    config.authentication_method = :authenticate_refinery_user!

ActiveAdmin-Settings should make use of this authentication method, but it does not (for now). To work around that problem you can hack it (I've put this in lib load with an initializer). (Still only solves the problem for that controller, but it's a start)

```ruby
ActiveadminSettings::SettingsController.class_eval do
  def authenticate_admin_user!
    send ActiveAdmin.application.authentication_method
  end
end
```
