### ISSUE TITLE
ArgumentError: 'ActiveadminSettings/pictures' is not a supported controller name

### ISSUE THREAD

**Issue by agustindidiego** [slate-studio/activeadmin-settings#21]
I'm getting this error just after adding the activeadmin-settings gem, and installing it.
after running bundle install, I run:
rake activeadmin_settings:install
rake activeadmin_settings:install:migrations

when I try to run rake db:migrate, I get the exception:
ArgumentError: 'ActiveadminSettings/pictures' is not a supported controller name. This can lead to potential routing problems. See http://guides.rubyonrails.org/routing.html#specifying-a-controller-to-use

I'm using Rails 4.0.4 with Ruby 2.1.1

**Comment by dangodev** [comment]
This fixed it for me as well; was using RubyGems rather than GH
